# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0cb05864b0c846f48dbe2e5772dde2ca"
application_url = "https://ripe-structures-lopez-nz.trycloudflare.com"
embedded = true
name = "checkout-policyconsent"
handle = "checkout-policyconsent"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ripe-structures-lopez-nz.trycloudflare.com/auth/callback",
  "https://ripe-structures-lopez-nz.trycloudflare.com/auth/shopify/callback",
  "https://ripe-structures-lopez-nz.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
